#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 400
#define SCREEN_HEIGHT 1000
#define TARGET_FPS 60
#define GRAVITY 15

#define PLAYER_IDLE_FRAMES 1
#define PLAYER_JUMP_FRAMES 2
#define PLAYER_MOVE_FRAMES 4
#define PLAYER_LANDING_FRAMES 6
#define PLAYER_FALLING_LOOP_FRAMES 3
#define PLAYER_FALLING_START_FRAMES 4

#endif